// ─── STATIC PRODUCT CATALOG ───────────────────────────────────────────────────

export const CATEGORY_META = {
  identities: {
    label: "IDENTITIES",
    sub: "MASKS . COSTUME",
    description: "Hand-sculpted character masks and identity pieces. Produced in controlled batches — no two runs are identical.",
    img: "/categories/category-identities.jpg",
    fallback: "/story1.jpg",
  },
  armory: {
    label: "ARMORY",
    sub: "COSTUME . ARMOUR",
    description: "Full costume armour sets and wearable character builds. From cyberpunk plate to ceremonial chainwork.",
    img: "/categories/category-armory.jpg",
    fallback: "/story3.jpg",
  },
  arsenal: {
    label: "ARSENAL",
    sub: "KATANAS . PROPS",
    description: "Character-accurate prop weapons. Katanas, blades, and display pieces with hand-applied finishes.",
    img: "/categories/category-arsenal.jpg",
    fallback: "/oni.jpg",
  },
  accessories: {
    label: "ACCESSORIES",
    sub: "PENDANTS . EARRINGS . BRACELETS",
    description: "Handcrafted character accessories. Pendants, earrings, bracelets and wearable detail pieces.",
    img: "/categories/category-accessories.jpg",
    fallback: "/story2.jpg",
  },
  apparel: {
    label: "APPAREL",
    sub: "CLOTHING . GEAR",
    description: "Wearable character gear. Hoodies, jackets, and layering pieces built for the identity.",
    img: "/categories/category-apparel.jpg",
    fallback: "/story4.jpg",
  },
};

export const STATIC_PRODUCTS = {
  identities: [
    {
      id: "id-mecha-maul",
      name: "ID. MECHA MAUL",
      sub: "CYBERPUNK MASK",
      price: "USD 325",
      amount: 32500,
      currency: "USD",
      image: "/products/product-mecha-maul.png",
      note: "5 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Cyberpunk oni-demon hybrid. Hand-sculpted clay base with digital design overlay and metallic paint finish. Full face coverage. Limited batch — each piece individually hand-painted.",
    },
    {
      id: "id-samson-robot",
      name: "ID. SAMSON | ROBOT",
      sub: "CYBERPUNK MASK",
      price: "USD 280",
      amount: 28000,
      currency: "USD",
      image: "/products/product-samson-robot.png",
      note: null,
      description: "Mechanical android face. Synthetic polymer shell with brushed metallic finish. Lightweight full-face design with deep eye cavity.",
    },
    {
      id: "id-samson-flesh",
      name: "ID. SAMSON | FLESH",
      sub: "CYBERPUNK MASK",
      price: "USD 280",
      amount: 28000,
      currency: "USD",
      image: "/products/product-samson-flesh.png",
      note: null,
      description: "Flesh-tone android variant. Hyper-realistic synthetic skin texture over rigid polymer shell. Unsettling realism at close range.",
    },
    {
      id: "id-samson-shaman",
      name: "ID. SAMSON | SHAMAN",
      sub: "CYBERPUNK MASK",
      price: "USD 300",
      amount: 30000,
      currency: "USD",
      image: "/products/product-samson-shaman.png",
      note: "3 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Oni shaman variant. Crimson lacquer over sculpted resin. Gold accent detailing with hand-applied war-paint finish.",
    },
    {
      id: "id-oni-crimson",
      name: "ID. ONI | CRIMSON",
      sub: "CYBERPUNK MASK",
      price: "USD 325",
      amount: 32500,
      currency: "USD",
      image: "/products/product-oni-crimson.png",
      note: null,
      description: "Deep crimson oni mask. Sculptural horns with gloss lacquer. Black circuit-pattern etching across brow and jaw.",
    },
    {
      id: "id-oni-nightvision",
      name: "ID. ONI | NIGHT VISION",
      sub: "CYBERPUNK MASK",
      price: "USD 325",
      amount: 32500,
      currency: "USD",
      image: "/products/product-oni-nightvision.png",
      note: null,
      description: "Night vision tactical oni. Matte black base with fluorescent green visor accents. Built for the dark.",
    },
    {
      id: "id-jeffrey-woods",
      name: "ID. JEFFREY WOODS",
      sub: "HALLOWEEN MASK | JEFF THE KILLER | CREEPY-PASTA",
      price: "USD 240+",
      amount: 24000,
      currency: "USD",
      image: "/products/product-jeffrey-woods.png",
      note: "8 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Full-face Jeff the Killer latex mask. Distorted smile, sunken eyes, pallid skin texture. Iconic creepypasta identity. Hand-finished each run.",
    },
    {
      id: "id-clown",
      name: "ID. CLOWN",
      sub: "HALLOWEEN MASK | CLOWN MASK",
      price: "USD 230",
      amount: 23000,
      currency: "USD",
      image: "/products/product-clown.png",
      note: null,
      description: "Classic horror clown full-face mask. White base, exaggerated features, hand-painted detailing. Full latex construction.",
    },
    {
      id: "id-necrosis",
      name: "ID. NECROSIS",
      sub: "ZOMBIE HALLOWEEN MASK",
      price: "USD 315+",
      amount: 31500,
      currency: "USD",
      image: "/products/product-necrosis.png",
      note: null,
      description: "Decomposed skull-face latex mask. Deep tissue decay detailing with exposed bone sections. High-detail horror finish.",
    },
    {
      id: "id-ferryman",
      name: "ID. FERRYMAN",
      sub: "FERRYMAN MASK | ANABELLE",
      price: "USD 235",
      amount: 23500,
      currency: "USD",
      image: "/products/product-ferryman.png",
      note: "5 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Weathered stone ferryman face mask. Ancient, hollow-eyed design. Textured grey finish with deep shadow detail.",
    },
    {
      id: "id-nun",
      name: "ID. NUN",
      sub: "THE NUN MASK | VALAK | CONJURING",
      price: "USD 245+",
      amount: 24500,
      currency: "USD",
      image: "/products/product-nun.png",
      note: "11 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Valak full-face latex mask. Cracked white skin, sunken black eyes, yellow iris. As seen in The Conjuring universe.",
    },
    {
      id: "id-candle-maker",
      name: "ID. CANDLE-MAKER",
      sub: "HALLOWEEN MASK",
      price: "USD 225",
      amount: 22500,
      currency: "USD",
      image: "/products/product-candle-maker.png",
      note: null,
      description: "Pale grinning horror mask with cracked wax-like skin texture. Wide fixed smile, hollow dark eyes. Disturbing close-up detail.",
    },
    {
      id: "id-bashee",
      name: "ID. BASHEE",
      sub: "HALLOWEEN MASK",
      price: "USD 245",
      amount: 24500,
      currency: "USD",
      image: "/products/product-bashee.png",
      note: "1 PERSON HAS THIS IN THEIR BASKET",
      description: "Open-mouthed banshee scream mask. Extreme facial distortion, elongated jaw. High-detail latex with dark textural finish.",
    },
    {
      id: "id-smiling-man",
      name: "ID. SMILING MAN",
      sub: "HALLOWEEN MASK | UNCANNY VALLEY MASK",
      price: "USD 225",
      amount: 22500,
      currency: "USD",
      image: "/products/product-smiling-man.png",
      note: null,
      description: "Uncanny valley full-face latex mask. Realistic human features distorted into permanent wide smile. Original version.",
    },
    {
      id: "id-smiling-man-2",
      name: "ID. SMILINGMAN 2.0",
      sub: "HALLOWEEN MASK | UNCANNY VALLEY MASK",
      price: "USD 250+",
      amount: 25000,
      currency: "USD",
      image: "/products/product-smiling-man-2.png",
      note: null,
      description: "Version 2.0 with improved chin articulation and refined skin texture. Deeper uncanny valley effect.",
    },
    {
      id: "id-smiling-man-3",
      name: "ID. SMILING MAN 3.0",
      sub: "HALLOWEEN MASK | UNCANNY VALLEY MASK",
      price: "USD 235+",
      amount: 23500,
      currency: "USD",
      image: "/products/product-smiling-man-3.png",
      note: null,
      description: "Version 3.0 — full flesh-tone latex with wider jaw and improved brow articulation. The definitive smiling man.",
    },
  ],
  armory: [
    {
      id: "armory-mech-glove",
      name: "EQUIP. MECHANICAL GLOVE",
      sub: "CYBERPUNK EXOSKELETON GAUNTLET",
      price: "USD 360+",
      amount: 36000,
      currency: "USD",
      image: "/products/product-mech-glove.png",
      note: "6 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Full exoskeleton gauntlet. Articulated finger plates over reinforced glove base. Gunmetal and carbon finish. Sold individually or as a pair.",
    },
    {
      id: "armory-mech-glove-2",
      name: "EQUIP. MECHANICAL GLOVE 2.0",
      sub: "CYBERPUNK EXOSKELETON GAUNTLET",
      price: "USD 425+",
      amount: 42500,
      currency: "USD",
      image: "/products/product-mech-glove-2.png",
      note: "5 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Upgraded gauntlet with reinforced knuckle plating and extended wrist guard. Improved articulation on all finger joints.",
    },
    {
      id: "armory-mech-bicep",
      name: "EQUIP. MECHANICAL BICEP",
      sub: "CYBERPUNK ARM EXTENSION",
      price: "USD 300+",
      amount: 30000,
      currency: "USD",
      image: "/products/product-mech-bicep.png",
      note: "3 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Dual-strap mechanical bicep extension. Pairs with the Mechanical Glove series. Adjustable fit, carbon-weave finish.",
    },
  ],
  arsenal: [
    {
      id: "arsenal-katana-crimson",
      name: "KATANA | CRIMSON EDGE",
      sub: "PROP BLADE",
      price: "USD 370+",
      amount: 37000,
      currency: "USD",
      image: "/categories/category-arsenal.jpg",
      note: null,
      description: "Hand-finished prop katana. Aluminium core, ABS tsuba, red lacquer handle wrap. 100cm overall length.",
    },
    {
      id: "arsenal-mech-blade",
      name: "MECHANICAL BLADE",
      sub: "PROP WEAPON",
      price: "USD 370+",
      amount: 37000,
      currency: "USD",
      image: "/categories/category-arsenal.jpg",
      note: null,
      description: "Cyberpunk mechanical arm-blade prop. Sculpted resin casing over aluminium rod. Light-reactive surface finish.",
    },
  ],
  accessories: [
    {
      id: "acc-black-dynasty",
      name: "BLACK DYNASTY BRACELET",
      sub: "METAL | HAND-CRAFTED",
      price: "USD 45",
      amount: 4500,
      currency: "USD",
      image: "/products/product-black-dynasty.png",
      note: null,
      description: "Hand-crafted metal link bracelet. Interlocking scale-pattern links in matte black finish. One size, adjustable clasp.",
    },
    {
      id: "acc-oni-pendant",
      name: "ONI PENDANT | SILVER",
      sub: "PENDANT",
      price: "USD 65",
      amount: 6500,
      currency: "USD",
      image: "/categories/category-accessories.jpg",
      note: null,
      description: "Hand-cast oni pendant. 30mm face, 3mm bail. Comes on 60cm black cord or 55cm chain.",
    },
  ],
  apparel: [
    {
      id: "app-black-hoodie",
      name: "SAVECHANGES HOODIE",
      sub: "HEAVYWEIGHT HOODIE",
      price: "USD 110",
      amount: 11000,
      currency: "USD",
      image: "/categories/category-apparel.jpg",
      note: null,
      description: "450gsm heavyweight fleece. Embroidered chest logo. Dropped shoulder. Sizes XS–3XL. Washed black.",
    },
    {
      id: "app-cargo-jacket",
      name: "IDENTITY JACKET",
      sub: "CARGO JACKET",
      price: "USD 195",
      amount: 19500,
      currency: "USD",
      image: "/categories/category-apparel.jpg",
      note: "3 PEOPLE HAVE THIS IN THEIR BASKET",
      description: "Multi-pocket cargo jacket with embroidered skull back-patch. Relaxed fit, zip and snap front. Sizes S–2XL.",
    },
  ],
};
